name: CMake-Release

on:
  release:
    types: [prereleased]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  # The number of days to retain artifacts
  RETENTION_DAYS: 30

jobs:
  build-msvc-win32:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure CMake MSVC 32-bit
        run: mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -A Win32
      - name: Build MSVC 32-bit
        run: cmake --build build --config ${{env.BUILD_TYPE}}
      - uses: actions/upload-artifact@v4
        with:
          name: obsidian-msvc-win32
          path: |
            addons
            data
            engines
            games
            language
            modules
            ports
            presets
            scripts
            theme
            tools
            obsidian.exe
          retention-days: ${{env.RETENTION_DAYS}}
  build-msvc-win64:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure CMake MSVC 64-bit
        run: mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      - name: Build MSVC 64-bit
        run: cmake --build build --config ${{env.BUILD_TYPE}}
      - uses: actions/upload-artifact@v4
        with:
          name: obsidian-msvc-win64
          path: |
            addons
            data
            engines
            games
            language
            modules
            ports
            presets
            scripts
            theme
            tools
            obsidian.exe
          retention-days: ${{env.RETENTION_DAYS}} 