name: CMake-Release

on:
  release:
    types: [prereleased]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  # The number of days to retain artifacts
  RETENTION_DAYS: 30

jobs:
  build-mingw-win32:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download w64devkit
        run: invoke-webrequest https://github.com/skeeto/w64devkit/releases/download/v1.23.0/w64devkit-i686-1.23.0.zip -outfile ${{github.workspace}}\w64devkit.zip
      - name: Extract w64devkit
        run: expand-archive -path ${{github.workspace}}\w64devkit.zip -destinationpath ${{github.workspace}}
      - name: Set environment variables and build
        run: |
          $env:Path = "${{github.workspace}}\w64devkit\bin;" + $env:Path
          cmake -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_CXX_FLAGS="-isystem ${{github.workspace}}\w64devkit\include" -DCMAKE_C_FLAGS="-isystem ${{github.workspace}}\w64devkit\include" -G "MinGW Makefiles"
          cmake --build build --config ${{env.BUILD_TYPE}}
          strip ${{github.workspace}}\obsidian.exe
      - uses: actions/upload-artifact@v4
        with:
          name: obsidian-mingw-win32
          path: |
            addons
            data
            engines
            games
            language
            modules
            ports
            presets
            scripts
            theme
            tools
            obsidian.exe
          retention-days: ${{env.RETENTION_DAYS}}
  build-msvc-win64:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure CMake MSVC 64-bit
        run: mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      - name: Build MSVC 64-bit
        run: cmake --build build --config ${{env.BUILD_TYPE}}
      - uses: actions/upload-artifact@v4
        with:
          name: obsidian-msvc-win64
          path: |
            addons
            data
            engines
            games
            language
            modules
            ports
            presets
            scripts
            theme
            tools
            obsidian.exe
          retention-days: ${{env.RETENTION_DAYS}} 